force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Detail__c/Product_Detail__c.object-meta.xml
<CustomObject>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>PD{0000}</displayFormat>
        <label>Product Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductDetailController.cls
/*****************************************************************************************
Name: ProductDetailController
===============================================================================================
===============================================================================================
Purpose:
--------
Controller for LWC - displayProduct 
===============================================================================================
===============================================================================================
History
-------
VERSION       AUTHOR                  DATE               DETAIL
1.0           Ashish           		29-Aug-2021      Initial Development
******************************************************************************************/

public with sharing class ProductDetailController {
    
    /********************************************************************************
     **Method Name- getProductDetails
     **Parameters- Id of Case record
     **Return type: list of Product Detail record
     **Description- This method accepts case Id and return list of product detail records
		on the basis of associated contact.
    ***********************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Product_Detail__c> getProductDetails(String caseId){
        String productId;
        String homeCountryId;
        List<Contact> contactRecord;
        List<Product_Detail__c> productDetailRecord;
        
        //Null check on caseId
        if(caseId != null){
            //Fetch Contact record using Contact Id on Case
            contactRecord = Utility.getContactFromCaseId(caseId);
        }
        
        //Null check on Contact record
        if(contactRecord !=null && !contactRecord.isEmpty()){
            //Set value for Product Id and Country Id
            productId = contactRecord[0].Product__c;
            homeCountryId = contactRecord[0].Home_Country__c;
        }
        
        //Null check on Product Id and Country Id
        if(productId != null && homeCountryId!= null){
            //Fetch Product Detail record using Product Id and Country Id
            productDetailRecord = Utility.getProductDetailRecord(productId,homeCountryId);
        }
        
        //Null check on Product Detail record and return the record
        if(productDetailRecord != null && !productDetailRecord.isEmpty()){
        	return productDetailRecord;
        }
        
        //Return null if Product Detail record is not fetched
        return null;
    }
}